Juju refactor code and update endpoints
grnet/ansible-inventory-server pull request #9
Opened 2019-11-19 08:23 UTC by neoaggelos

Refactored Juju endpoints.
    
* Replaced old Louros-specific endpoints with a richer `GET /juju/machines`, which returns list of machines along with list of Juju applications and containers running on top of them, instead of only their IP addresses.
* Updated code readability. Removed duplicate code.
* Refactored Juju model and get status code
* Follow a specific code style throughout the code
   
Also note that these changes are required in order to move on to creating inventories that combine information from both MaaS and Juju.

Fixes #8

2019-11-21 12:15 UTC, skatsaounis requested changes

2019-11-21 12:15 UTC, skatsaounis commented on ansible_inventory_server/jujurest.py
> +    if not model.is_connected():
'NoneType' object has no attribute 'is_connected' : if an error occurs in get_juju_model it returns None

2019-11-22 10:30 UTC, neoaggelos commented on ansible_inventory_server/jujurest.py
> +    if not model.is_connected():
Updated to always return the model

2019-11-22 10:38 UTC, skatsaounis approved these changes

2019-11-22 10:38 UTC, merged